export const SET_COMPANY = 'SET_COMPANY';

export const GET_CALENDAR_START = 'GET_CALENDAR_START';
export const GET_CALENDAR_SUCCESS = 'GET_CALENDAR_SUCCESS';
export const GET_CALENDAR_FAIL = 'GET_CALENDAR_FAIL';
