export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const EXTERNAL_LOGIN_START = 'EXTERNAL_LOGIN_START';
export const EXTERNAL_LOGIN_SUCCESS = 'EXTERNAL_LOGIN_SUCCESS';
export const EXTERNAL_LOGIN_FAIL = 'EXTERNAL_LOGIN_FAIL';

export const EXTERNAL_LOGIN_CALLBACK_START = 'EXTERNAL_LOGIN_CALLBACK_START';
export const EXTERNAL_LOGIN_CALLBACK_SUCCESS = 'EXTERNAL_LOGIN_CALLBACK_SUCCESS';
export const EXTERNAL_LOGIN_CALLBACK_FAIL = 'EXTERNAL_LOGIN_CALLBACK_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
