// CLIENTS

export const GET_ALL_CLIENTS_START = 'GET_ALL_CLIENTS_START';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_FAIL = 'GET_ALL_CLIENTS_FAIL';

export const SEARCH_CLIENTS_START = 'SEARCH_CLIENTS_START';
export const SEARCH_CLIENTS_SUCCESS = 'SEARCH_CLIENTS_SUCCESS';
export const SEARCH_CLIENTS_FAIL = 'SEARCH_CLIENTS_FAIL';

export const GET_CLIENT_START = 'GET_CLIENT_START';
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS';
export const GET_CLIENT_FAIL = 'GET_CLIENT_FAIL';

export const ADD_CLIENT_START = 'ADD_CLIENT_START';
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS';
export const ADD_CLIENT_FAIL = 'ADD_CLIENT_FAIL';

export const EDIT_CLIENT_START = 'EDIT_CLIENT_START';
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export const EDIT_CLIENT_FAIL = 'EDIT_CLIENT_FAIL';

export const DELETE_CLIENT_START = 'DELETE_CLIENT_START';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAIL = 'DELETE_CLIENT_FAIL';

export const ADD_WORKING_DAYS_START = 'ADD_WORKING_DAYS_START';
export const ADD_WORKING_DAYS_SUCCESS = 'ADD_WORKING_DAYS_SUCCESS';
export const ADD_WORKING_DAYS_FAIL = 'ADD_WORKING_DAYS_FAIL';

// INVOICES

export const SEARCH_INVOICES_START = 'SEARCH_INVOICES_START';
export const SEARCH_INVOICES_SUCCESS = 'SEARCH_INVOICES_SUCCESS';
export const SEARCH_INVOICES_FAIL = 'SEARCH_INVOICES_FAIL';

export const GET_INVOICE_START = 'GET_INVOICE_START';
export const GET_INVOICE_SUCCESS = 'GET_INVOICE_SUCCESS';
export const GET_INVOICE_FAIL = 'GET_INVOICE_FAIL';

export const ADD_INVOICE_START = 'ADD_INVOICE_START';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAIL = 'ADD_INVOICE_FAIL';

export const EDIT_INVOICE_START = 'EDIT_INVOICE_START';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_FAIL = 'EDIT_INVOICE_FAIL';

export const DELETE_INVOICE_START = 'DELETE_INVOICE_START';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL';